language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - py.test --pep8 sevenbridges --cov sevenbridges
  - flake8 sevenbridges

deploy:
  provider: pypi
  user: sbg
  password:
    secure: YGPYAH/pB8dmI62LeXXz9sDoswMud74uo/b92TFTanbNaD6AV7PwEWEtJOyj9+aDvPuDfTxvidxgNetNZ3bO923sA2xQYIn/iirjC9NQa7MCjtIqpAKUmdfXKhUuRu1J/XuTIhRSKkcXPZirOg2LQ/lhHP3h2biAgiio2nqMCW47t1I/TMZAt4mebsD3vXljeiS66GwFY3yKB7mOXbQpDRKRGE1Yr+NeiPsdsgtZY2g2sWDyXgBwJgq1+Y2/F3g7c98j2kCfNieaZ9SpG7Ecdgk818Jkq7AzRNPvdECUVqTYDNMz3RMd/Xq9bbrP6eg600QHDoMmIqO9qRjtatC+uH5rqwt/UQKnL7xgFI10ktwkYOZ/yarov63ltPQStE1+yUoFMg0Jp61r5zXlsjiwtOk4aKSZS0DPrJtq+vSG3eJwDYgifMk+lVnO0QJ+BTe1HSHQIDdQ3epOswTljo6g9fRJPyS8bB+3Me56bWn4t7vFfvSeBDT5XfnJm2FeV/4oRR7NgRcfZ7IlPeBn4Ql1n5GPHBq2CVwKjP3fj17t5McjdF+IoJqDxWt2ops+QOABFn2qtmEmpUM7frFF8RWkXfpqMOAdvvOSsBj/Nb+vyMHCqs+8LCFrhBL4VXEw9REz3RwR7yl5VWxWzj6BHupILzgs0EVNyXJJ78eFA0KvQPU=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-python
